=== bobAnthonyVarley/Info-Management-Group-7/Hospital.dtd
<!ELEMENT Hospital 
    (Hospital.hospitalName, Hospital.hospitalLocation, Hospita.avaiability, Hospital.encryptionModule, Hospital.patientChart, Hospital.hospitalDatabase)>

<!ELEMENT Hospital.hospitalName (#PCDATA)>

<!ELEMENT Hospital.hospitalLocation (value+)>
<!ATTLIST Hospital.hospitalLocation type NMTOKEN #REQUIRED>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value name NMTOKEN #REQUIRED>

<!ELEMENT Hospita.avaiability (#PCDATA)>
<!ATTLIST Hospita.avaiability type NMTOKEN #REQUIRED>

<!ELEMENT Hospital.encryptionModule (EndcryptionModule)>
<!ELEMENT EndcryptionModule (EncryptionModule.key,EncryptionModule.dataToEncrypt)>
<!ELEMENT EncryptionModule.key (#PCDATA)>
<!ATTLIST EncryptionModule.key type NMTOKEN #REQUIRED>
<!ELEMENT EncryptionModule.dataToEncrypt (#PCDATA)>

<!ELEMENT Hospital.patientChart (PatientChart)>
<!ELEMENT PatientChart (#PCDATA)>

<!ELEMENT Hospital.hospitalDatabase (patientChart+)>
<!ATTLIST Hospital.hospitalDatabase type NMTOKEN #REQUIRED>
<!ELEMENT patientChart (#PCDATA)>

=== bobAnthonyVarley/Info-Management-Group-7/Hospital.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Hospital SYSTEM 'Hospital.dtd'>
<Hospital>
    <Hospital.hospitalName>St. James Hospital</Hospital.hospitalName>
    <Hospital.hospitalLocation type = "array">
        <value name ="longitude">53.33886</value>
        <value name = "latitude">-6.297293</value>
    </Hospital.hospitalLocation>
    <Hospita.avaiability type="boolean">true</Hospita.avaiability>
    <Hospital.encryptionModule> 
        <EndcryptionModule>
            <EncryptionModule.key type = "array">
                <!-- same key for all documents?-->
            </EncryptionModule.key>
            <EncryptionModule.dataToEncrypt>
                <!-- what is the data to encrypt?-->
            </EncryptionModule.dataToEncrypt>
        </EndcryptionModule>
    </Hospital.encryptionModule>
    <Hospital.patientChart>
        <PatientChart>

        </PatientChart>
    </Hospital.patientChart>
    <Hospital.hospitalDatabase type = "arrayList"> 
        <patientChart>John Doe</patientChart> 
        <patientChart>Jane Doe</patientChart> 
        <patientChart>Mario Rossi</patientChart> 
    </Hospital.hospitalDatabase>
</Hospital>
